[package]
name = "async_zip_tokio_example"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
async_zip = { version = "0.0.17", features = ["full"] }
chrono = "0.4.41"
tokio = { version = "1.45.1", features = ["full"] }
tokio-util = { version = "0.7.15", features = ["compat"] }
